/**
 * Catálogo DEMO. Textos ILUSTRATIVOS, redigidos de forma genérica a partir dos padrões mais frequentes no corpus
 * (banca 53%, conservatórias/registos 37%, tribunais 14%, substabelecimento 14%, fiscal 14%, imóveis 12%, menores 12%…).
 * NÃO são textos juridicamente validados. Todos ficam marcados is_demo = true.
 */
type F = { chave: string; rotulo: string; tipo: string; obrigatorio: boolean; opcoes?: { valor: string; rotulo: string }[]; moeda?: string; validacao?: object; textoVerdadeiro?: string };
type R = { tipo: 'REQUER' | 'INCOMPATIVEL' | 'SUGERE'; alvoCodigo: string };
export interface PoderDemo { codigo: string; categoria: string; nome: string; descricao: string; texto: string; campos?: F[]; regras?: R[]; tipo?: 'PODER' | 'CLAUSULA'; exclusivo?: boolean; tiposPermitidos?: string[]; textoAlternativo?: string }

const t = (chave: string, rotulo: string, obrigatorio = true): F => ({ chave, rotulo, tipo: 'TEXTO', obrigatorio });
const ent = (chave: string, rotulo: string): F => ({ chave, rotulo, tipo: 'ENTIDADE', obrigatorio: true });
const pes = (chave: string, rotulo: string): F => ({ chave, rotulo, tipo: 'PESSOA', obrigatorio: true });
const REQ = (c: string): R => ({ tipo: 'REQUER', alvoCodigo: c });
const SUG = (c: string): R => ({ tipo: 'SUGERE', alvoCodigo: c });
const INC = (c: string): R => ({ tipo: 'INCOMPATIVEL', alvoCodigo: c });
const OPS_BANC = [
  { valor: 'mov', rotulo: 'movimentar e actualizar a conta' }, { valor: 'ext', rotulo: 'solicitar extractos bancários' }, { valor: 'tnac', rotulo: 'efectuar transferências nacionais' },
  { valor: 'tint', rotulo: 'efectuar transferências internacionais' }, { valor: 'dep', rotulo: 'fazer depósitos' }, { valor: 'lev', rotulo: 'fazer levantamentos' },
  { valor: 'chq', rotulo: 'requisitar, levantar e assinar cheques' }, { valor: 'cart', rotulo: 'solicitar a emissão e o levantamento de cartões de débito e crédito e respectivos códigos' },
  { valor: 'net', rotulo: 'solicitar credenciais de banca electrónica' },
];

export const CATEGORIAS: [string, string][] = [
  ['BANCARIOS', 'Bancários e financeiros'], ['IMOBILIARIOS', 'Imobiliários'], ['COMERCIAIS', 'Comerciais'], ['EMPRESARIAIS', 'Empresariais'], ['FISCAIS', 'Fiscais'],
  ['ADUANEIROS', 'Aduaneiros'], ['ADMINISTRATIVOS', 'Administrativos'], ['JUDICIAIS', 'Judiciais'], ['AUTOMOVEIS', 'Automóveis'], ['SEGUROS', 'Seguros'],
  ['SOCIETARIOS', 'Societários'], ['LABORAIS', 'Laborais e segurança social'], ['ENT_PUBLICAS', 'Representação perante entidades públicas'], ['ENT_PRIVADAS', 'Representação perante entidades privadas'],
  ['COMPRA_VENDA', 'Compra e venda'], ['ARRENDAMENTO', 'Arrendamento'], ['HERANCAS', 'Heranças e sucessões'], ['REGISTOS', 'Registos (civil, predial, comercial)'], ['NOTARIADO', 'Notariado'],
  ['MENORES', 'Menores e responsabilidades parentais'], ['GERAL', 'Procuração geral'], ['ESPECIAL', 'Procuração especial'], ['CLAUSULAS', 'Cláusulas finais'], ['OUTROS', 'Outros'],
];

export const PODERES: PoderDemo[] = [
  // Bancários
  { codigo: 'BANC-001', categoria: 'BANCARIOS', nome: 'Representação junto de instituição bancária', descricao: 'Representação genérica perante um banco identificado.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} junto do {{banco}}{{#if agencia}}, agência {{agencia}}{{/if}}, em todos os assuntos relacionados com as contas de que {{flex outorgantes "seja titular" "seja titular" "sejam titulares" "sejam titulares"}}', campos: [ent('banco', 'Banco'), t('agencia', 'Agência', false)], regras: [SUG('BANC-002'), SUG('BANC-003')] },
  { codigo: 'BANC-002', categoria: 'BANCARIOS', nome: 'Movimentação de conta bancária', descricao: 'Operações sobre uma conta concreta, com limite opcional.', texto: 'relativamente à conta {{#if iban}}com o IBAN {{iban}}{{else}}n.º {{numero_conta}}{{/if}}, {{operacoes}}{{#if limite}}, até ao limite de {{limite}} por operação{{/if}}', campos: [{ chave: 'iban', rotulo: 'IBAN', tipo: 'IBAN', obrigatorio: false }, t('numero_conta', 'N.º de conta (se não houver IBAN)', false), { chave: 'operacoes', rotulo: 'Operações autorizadas', tipo: 'SELECCAO_MULTIPLA', obrigatorio: true, opcoes: OPS_BANC }, { chave: 'limite', rotulo: 'Limite por operação', tipo: 'MOEDA', obrigatorio: false, moeda: 'AOA' }], regras: [REQ('BANC-001')] },
  { codigo: 'BANC-003', categoria: 'BANCARIOS', nome: 'Actualização de dados e assinaturas', descricao: 'Actualização cadastral e de fichas de assinatura.', texto: 'actualizar os dados cadastrais e as fichas de assinatura, assinando todos os formulários necessários', regras: [REQ('BANC-001')] },
  { codigo: 'BANC-004', categoria: 'BANCARIOS', nome: 'Abertura de conta bancária', descricao: 'Abrir conta em nome do outorgante.', texto: 'abrir conta de depósitos à ordem em nome {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}} no {{banco}}, subscrevendo os respectivos contratos', campos: [ent('banco', 'Banco')] },
  { codigo: 'BANC-005', categoria: 'BANCARIOS', nome: 'Encerramento de conta bancária', descricao: 'Encerrar conta e receber saldo.', texto: 'encerrar a conta n.º {{numero_conta}} junto do {{banco}} e receber o respectivo saldo', campos: [ent('banco', 'Banco'), t('numero_conta', 'N.º de conta')], regras: [INC('BANC-004')] },
  { codigo: 'BANC-006', categoria: 'BANCARIOS', nome: 'Contratação de crédito', descricao: 'Negociar e contratar crédito até montante.', texto: 'negociar e contratar crédito junto do {{banco}} até ao montante de {{montante}}, prestando as garantias que se mostrem necessárias', campos: [ent('banco', 'Banco'), { chave: 'montante', rotulo: 'Montante máximo', tipo: 'MOEDA', obrigatorio: true, moeda: 'AOA' }], regras: [SUG('BANC-001')] },
  { codigo: 'BANC-007', categoria: 'BANCARIOS', nome: 'Levantamento de cartão e códigos', descricao: 'Levantar cartões e PIN.', texto: 'solicitar e levantar cartões de débito e de crédito e os respectivos códigos secretos, bem como efectuar os seus carregamentos', regras: [REQ('BANC-001')] },
  // Imobiliários / compra e venda / arrendamento
  { codigo: 'IMOV-001', categoria: 'IMOBILIARIOS', nome: 'Venda de imóvel', descricao: 'Vender imóvel identificado, com preço mínimo.', texto: 'vender, pelo preço e condições que entender, mas nunca inferior a {{preco_minimo}}, o {{imovel}}, outorgando e assinando a respectiva escritura ou documento particular autenticado', campos: [{ chave: 'imovel', rotulo: 'Imóvel', tipo: 'IMOVEL', obrigatorio: true }, { chave: 'preco_minimo', rotulo: 'Preço mínimo', tipo: 'MOEDA', obrigatorio: true, moeda: 'EUR' }], regras: [SUG('REG-002'), SUG('FISC-001'), SUG('IMOV-004'), SUG('IMOV-005'), INC('IMOV-002')], tiposPermitidos: ['IMOVEL_VENDA', 'ESPECIAL', 'GERAL'] },
  { codigo: 'IMOV-002', categoria: 'IMOBILIARIOS', nome: 'Compra de imóvel', descricao: 'Comprar imóvel identificado, com preço máximo.', texto: 'comprar, pelo preço máximo de {{preco_maximo}}, o {{imovel}}, podendo outorgar a respectiva escritura e pagar o preço', campos: [{ chave: 'imovel', rotulo: 'Imóvel', tipo: 'IMOVEL', obrigatorio: true }, { chave: 'preco_maximo', rotulo: 'Preço máximo', tipo: 'MOEDA', obrigatorio: true, moeda: 'EUR' }], regras: [SUG('REG-002'), SUG('FISC-001')], tiposPermitidos: ['IMOVEL_COMPRA', 'ESPECIAL', 'GERAL'] },
  { codigo: 'IMOV-003', categoria: 'IMOBILIARIOS', nome: 'Contrato-promessa', descricao: 'Celebrar contrato-promessa de compra e venda.', texto: 'celebrar contrato-promessa de compra e venda relativo ao {{imovel}}, recebendo ou entregando sinal', campos: [{ chave: 'imovel', rotulo: 'Imóvel', tipo: 'IMOVEL', obrigatorio: true }] },
  { codigo: 'IMOV-004', categoria: 'COMPRA_VENDA', nome: 'Receber o preço e dar quitação', descricao: 'Receber valores e emitir quitação.', texto: 'receber o preço ou quaisquer quantias devidas e dar a respectiva quitação' },
  { codigo: 'IMOV-005', categoria: 'IMOBILIARIOS', nome: 'Tratar documentação do imóvel', descricao: 'Certidões, cadernetas, licenças.', texto: 'requerer e levantar certidões, cadernetas prediais, licenças e demais documentos relativos ao imóvel' },
  { codigo: 'IMOV-006', categoria: 'IMOBILIARIOS', nome: 'Hipoteca', descricao: 'Constituir ou cancelar hipoteca.', texto: '{{accao}} hipoteca sobre o {{imovel}}', campos: [{ chave: 'accao', rotulo: 'Acção', tipo: 'RADIO', obrigatorio: true, opcoes: [{ valor: 'constituir', rotulo: 'constituir' }, { valor: 'cancelar', rotulo: 'requerer o cancelamento de' }] }, { chave: 'imovel', rotulo: 'Imóvel', tipo: 'IMOVEL', obrigatorio: true }] },
  { codigo: 'ARR-001', categoria: 'ARRENDAMENTO', nome: 'Dar de arrendamento', descricao: 'Arrendar imóvel do outorgante.', texto: 'dar de arrendamento o {{imovel}}, pela renda mensal mínima de {{renda}}, assinar o contrato e receber as rendas', campos: [{ chave: 'imovel', rotulo: 'Imóvel', tipo: 'IMOVEL', obrigatorio: true }, { chave: 'renda', rotulo: 'Renda mínima', tipo: 'MOEDA', obrigatorio: true, moeda: 'EUR' }] },
  { codigo: 'ARR-002', categoria: 'ARRENDAMENTO', nome: 'Tomar de arrendamento', descricao: 'Arrendar imóvel para o outorgante.', texto: 'tomar de arrendamento, para habitação {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}}, imóvel situado em {{localidade}}, assinando o respectivo contrato', campos: [t('localidade', 'Localidade')] },
  { codigo: 'ARR-003', categoria: 'ARRENDAMENTO', nome: 'Denúncia de arrendamento', descricao: 'Denunciar ou revogar contrato de arrendamento.', texto: 'denunciar, revogar ou resolver o contrato de arrendamento relativo ao {{imovel}}', campos: [{ chave: 'imovel', rotulo: 'Imóvel', tipo: 'IMOVEL', obrigatorio: true }] },
  // Registos
  { codigo: 'REG-001', categoria: 'REGISTOS', nome: 'Registo civil — certidões e assentos', descricao: 'Requerer certidões, averbamentos e rectificações.', texto: 'requerer junto da {{conservatoria}} certidões de {{actos}}, bem como averbamentos, rectificações e segundas vias', campos: [ent('conservatoria', 'Conservatória'), { chave: 'actos', rotulo: 'Actos', tipo: 'SELECCAO_MULTIPLA', obrigatorio: true, opcoes: [{ valor: 'nasc', rotulo: 'nascimento' }, { valor: 'cas', rotulo: 'casamento' }, { valor: 'obito', rotulo: 'óbito' }] }] },
  { codigo: 'REG-002', categoria: 'REGISTOS', nome: 'Registo predial', descricao: 'Actos de registo predial.', texto: 'requerer, junto de qualquer conservatória do registo predial, todos os actos de registo, provisórios ou definitivos, e respectivos cancelamentos' },
  { codigo: 'REG-003', categoria: 'REGISTOS', nome: 'Registo comercial', descricao: 'Actos de registo comercial.', texto: 'requerer, junto da conservatória do registo comercial, quaisquer actos de registo relativos à {{empresa}}', campos: [{ chave: 'empresa', rotulo: 'Sociedade', tipo: 'EMPRESA', obrigatorio: true }] },
  { codigo: 'REG-004', categoria: 'REGISTOS', nome: 'Rectificação de assento de nascimento', descricao: 'Correcção de assento.', texto: 'requerer a rectificação do assento de nascimento {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}}, relativamente a {{elemento}}', campos: [t('elemento', 'Elemento a rectificar')] },
  { codigo: 'REG-005', categoria: 'REGISTOS', nome: 'Instrução de processo de casamento', descricao: 'Organizar processo preliminar de casamento.', texto: 'instruir o processo preliminar de casamento junto da {{conservatoria}}, apresentando e levantando documentos', campos: [ent('conservatoria', 'Conservatória')] },
  { codigo: 'REG-006', categoria: 'REGISTOS', nome: 'Bilhete de Identidade — tratamento', descricao: 'Pedido ou renovação de BI.', texto: 'tratar de todos os assuntos relativos à emissão ou renovação do Bilhete de Identidade {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}}' },
  { codigo: 'REG-007', categoria: 'REGISTOS', nome: 'Passaporte — tratamento', descricao: 'Tratamento de passaporte (observado em 7% do corpus).', texto: 'tratar e levantar o passaporte {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}} junto dos serviços competentes' },
  // Judiciais
  { codigo: 'JUD-001', categoria: 'JUDICIAIS', nome: 'Mandato forense geral', descricao: 'Poderes forenses gerais (advogado).', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} em juízo e fora dele, com os poderes forenses gerais, intentando acções, contestando, recorrendo e acompanhando processos' },
  { codigo: 'JUD-002', categoria: 'JUDICIAIS', nome: 'Poderes forenses especiais', descricao: 'Confessar, desistir, transigir.', texto: 'confessar, desistir do pedido ou da instância e transigir, nos termos legalmente permitidos', regras: [REQ('JUD-001')] },
  { codigo: 'JUD-003', categoria: 'JUDICIAIS', nome: 'Processo determinado', descricao: 'Intervir em processo identificado.', texto: 'intervir no processo n.º {{processo}}, a correr termos no {{tribunal}}', campos: [t('processo', 'N.º do processo'), ent('tribunal', 'Tribunal')], regras: [SUG('JUD-001')] },
  { codigo: 'JUD-004', categoria: 'JUDICIAIS', nome: 'Receber citações e notificações', descricao: 'Receber actos de comunicação.', texto: 'receber citações, notificações e intimações' },
  { codigo: 'JUD-005', categoria: 'JUDICIAIS', nome: 'Constituir mandatário', descricao: 'Constituir advogado.', texto: 'constituir advogado, conferindo-lhe os poderes forenses legalmente admissíveis' },
  { codigo: 'JUD-006', categoria: 'JUDICIAIS', nome: 'Queixa e participação', descricao: 'Apresentar queixa criminal.', texto: 'apresentar queixa ou participação junto das autoridades competentes e prestar declarações' },
  // Heranças
  { codigo: 'HER-001', categoria: 'HERANCAS', nome: 'Habilitação de herdeiros', descricao: 'Habilitação por óbito de pessoa identificada.', texto: 'requerer e outorgar a habilitação de herdeiros por óbito de {{falecido}}, falecido em {{data_obito}}', campos: [t('falecido', 'Nome do falecido'), { chave: 'data_obito', rotulo: 'Data do óbito', tipo: 'DATA', obrigatorio: true }], regras: [SUG('HER-002'), SUG('REG-001')] },
  { codigo: 'HER-002', categoria: 'HERANCAS', nome: 'Partilha', descricao: 'Partilha de bens da herança.', texto: 'proceder à partilha dos bens da herança, aceitando ou repudiando tornas e assinando os respectivos documentos', regras: [REQ('HER-001')] },
  { codigo: 'HER-003', categoria: 'HERANCAS', nome: 'Repúdio de herança', descricao: 'Repudiar herança.', texto: 'repudiar a herança aberta por óbito de {{falecido}}', campos: [t('falecido', 'Nome do falecido')], regras: [INC('HER-002')] },
  // Fiscais / aduaneiros
  { codigo: 'FISC-001', categoria: 'FISCAIS', nome: 'Representação perante a administração tributária', descricao: 'Declarações, pagamentos, certidões.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} perante a {{administracao}}, apresentando declarações, efectuando pagamentos e requerendo certidões', campos: [ent('administracao', 'Administração tributária')] },
  { codigo: 'FISC-002', categoria: 'FISCAIS', nome: 'Pedido de NIF', descricao: 'Requerer número de identificação fiscal.', texto: 'requerer a atribuição de número de identificação fiscal' },
  { codigo: 'FISC-003', categoria: 'FISCAIS', nome: 'Reclamações e impugnações fiscais', descricao: 'Reclamar actos tributários.', texto: 'apresentar reclamações graciosas, recursos hierárquicos e impugnações', regras: [REQ('FISC-001')] },
  { codigo: 'ADU-001', categoria: 'ADUANEIROS', nome: 'Desalfandegamento', descricao: 'Tratar de despacho aduaneiro.', texto: 'tratar do desalfandegamento de {{mercadoria}}, junto dos serviços aduaneiros, pagando direitos e taxas', campos: [t('mercadoria', 'Bens/mercadoria')] },
  // Administrativos / entidades
  { codigo: 'ADM-001', categoria: 'ADMINISTRATIVOS', nome: 'Representação perante entidades públicas', descricao: 'Ministérios, serviços, institutos.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} perante quaisquer entidades públicas, nomeadamente {{entidades}}, apresentando requerimentos e levantando documentos', campos: [t('entidades', 'Entidades (enumerar)')] },
  { codigo: 'ADM-002', categoria: 'ENT_PRIVADAS', nome: 'Representação perante entidades privadas', descricao: 'Empresas, operadoras, prestadores.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} perante {{entidade}}, tratando de todos os assuntos relativos a {{assunto}}', campos: [ent('entidade', 'Entidade'), t('assunto', 'Assunto')] },
  { codigo: 'ADM-003', categoria: 'ADMINISTRATIVOS', nome: 'Assinar e levantar documentos', descricao: 'Poder instrumental.', texto: 'assinar requerimentos, declarações e recibos, e requerer e levantar quaisquer documentos' },
  { codigo: 'ADM-004', categoria: 'ADMINISTRATIVOS', nome: 'Pagar taxas e emolumentos', descricao: 'Poder instrumental.', texto: 'pagar taxas, emolumentos e demais despesas legalmente exigíveis' },
  { codigo: 'ADM-005', categoria: 'ENT_PRIVADAS', nome: 'Telecomunicações', descricao: 'Serviços de operadora (7% do corpus).', texto: 'tratar junto da {{operadora}} de todos os assuntos relativos ao número {{numero}}, incluindo segunda via de cartão e alteração de titularidade', campos: [ent('operadora', 'Operadora'), { chave: 'numero', rotulo: 'Número de telefone', tipo: 'TELEFONE', obrigatorio: true }] },
  // Laborais / segurança social
  { codigo: 'LAB-001', categoria: 'LABORAIS', nome: 'Segurança social — pensões', descricao: 'Prova de vida, pensões, prestações.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} junto do {{instituto}}, requerendo e recebendo pensões e demais prestações e fazendo prova de vida', campos: [ent('instituto', 'Instituição de segurança social')] },
  { codigo: 'LAB-002', categoria: 'LABORAIS', nome: 'Assuntos laborais', descricao: 'Perante entidade empregadora.', texto: 'tratar junto da entidade empregadora {{empregador}} de assuntos laborais, receber créditos salariais e assinar a documentação necessária', campos: [t('empregador', 'Entidade empregadora')] },
  // Societários / empresariais / comerciais
  { codigo: 'SOC-001', categoria: 'SOCIETARIOS', nome: 'Constituição de sociedade', descricao: 'Constituir sociedade comercial.', texto: 'constituir uma sociedade {{tipo_sociedade}} com a denominação {{denominacao}}, subscrevendo o capital, aprovando estatutos e praticando os actos de registo', campos: [{ chave: 'tipo_sociedade', rotulo: 'Tipo de sociedade', tipo: 'LISTA', obrigatorio: true, opcoes: [{ valor: 'quotas', rotulo: 'por quotas' }, { valor: 'unipessoal', rotulo: 'unipessoal por quotas' }, { valor: 'anonima', rotulo: 'anónima' }] }, t('denominacao', 'Denominação')], regras: [SUG('REG-003'), SUG('FISC-002')] },
  { codigo: 'SOC-002', categoria: 'SOCIETARIOS', nome: 'Assembleias gerais', descricao: 'Representar em assembleias e votar.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}} nas assembleias gerais da {{empresa}}, discutindo e votando as deliberações', campos: [{ chave: 'empresa', rotulo: 'Sociedade', tipo: 'EMPRESA', obrigatorio: true }] },
  { codigo: 'SOC-003', categoria: 'SOCIETARIOS', nome: 'Cessão de quotas', descricao: 'Ceder ou adquirir quota.', texto: '{{accao}} a quota com o valor nominal de {{valor}} na {{empresa}}', campos: [{ chave: 'accao', rotulo: 'Acção', tipo: 'RADIO', obrigatorio: true, opcoes: [{ valor: 'ceder', rotulo: 'ceder' }, { valor: 'adquirir', rotulo: 'adquirir' }] }, { chave: 'valor', rotulo: 'Valor nominal', tipo: 'MOEDA', obrigatorio: true, moeda: 'AOA' }, { chave: 'empresa', rotulo: 'Sociedade', tipo: 'EMPRESA', obrigatorio: true }] },
  { codigo: 'EMP-001', categoria: 'EMPRESARIAIS', nome: 'Gestão corrente da empresa', descricao: 'Actos de gestão corrente.', texto: 'praticar os actos de gestão corrente da {{empresa}}, perante quaisquer entidades públicas e privadas', campos: [{ chave: 'empresa', rotulo: 'Sociedade', tipo: 'EMPRESA', obrigatorio: true }] },
  { codigo: 'COM-001', categoria: 'COMERCIAIS', nome: 'Contratos comerciais', descricao: 'Negociar e assinar contratos.', texto: 'negociar e assinar contratos de fornecimento e de prestação de serviços até ao valor de {{valor}}', campos: [{ chave: 'valor', rotulo: 'Valor máximo', tipo: 'MOEDA', obrigatorio: true, moeda: 'USD' }] },
  // Automóveis / seguros
  { codigo: 'AUTO-001', categoria: 'AUTOMOVEIS', nome: 'Venda de veículo', descricao: 'Vender veículo identificado.', texto: 'vender o {{veiculo}}, pelo preço que entender, assinando o requerimento de registo de propriedade', campos: [{ chave: 'veiculo', rotulo: 'Veículo', tipo: 'VEICULO', obrigatorio: true }], regras: [INC('AUTO-002')] },
  { codigo: 'AUTO-002', categoria: 'AUTOMOVEIS', nome: 'Compra e registo de veículo', descricao: 'Adquirir e registar veículo.', texto: 'adquirir e registar em nome {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}} o {{veiculo}}', campos: [{ chave: 'veiculo', rotulo: 'Veículo', tipo: 'VEICULO', obrigatorio: true }] },
  { codigo: 'SEG-001', categoria: 'SEGUROS', nome: 'Contratos de seguro', descricao: 'Celebrar, alterar e participar sinistros.', texto: 'celebrar, alterar e resolver contratos de seguro, participar sinistros e receber indemnizações junto da {{seguradora}}', campos: [ent('seguradora', 'Seguradora')] },
  // Menores
  { codigo: 'MEN-001', categoria: 'MENORES', nome: 'Representação de filho menor', descricao: 'Actos relativos a filho menor.', texto: 'representar {{flex outorgantes "o outorgante" "a outorgante" "os outorgantes" "as outorgantes"}}, no exercício das responsabilidades parentais, em todos os assuntos relativos ao menor {{menor}}, nomeadamente {{assuntos}}', campos: [pes('menor', 'Menor'), { chave: 'assuntos', rotulo: 'Assuntos', tipo: 'SELECCAO_MULTIPLA', obrigatorio: true, opcoes: [{ valor: 'esc', rotulo: 'matrícula e assuntos escolares' }, { valor: 'saude', rotulo: 'assuntos de saúde' }, { valor: 'doc', rotulo: 'emissão de documentos de identificação' }, { valor: 'viag', rotulo: 'autorização de viagem' }] }] },
  { codigo: 'MEN-002', categoria: 'MENORES', nome: 'Autorização de viagem de menor', descricao: 'Viagem de menor acompanhado pelo procurador.', texto: 'acompanhar o menor {{menor}} em viagem para {{destino}}, entre {{data_inicio}} e {{data_fim}}', campos: [pes('menor', 'Menor'), t('destino', 'Destino'), { chave: 'data_inicio', rotulo: 'Início', tipo: 'DATA', obrigatorio: true }, { chave: 'data_fim', rotulo: 'Fim', tipo: 'DATA', obrigatorio: true }] },
  // Geral / especial / notariado
  { codigo: 'GER-001', categoria: 'GERAL', nome: 'Plenos poderes de administração', descricao: 'Procuração geral — não combinável.', texto: 'gerir e administrar todos os bens {{flex outorgantes "do outorgante" "da outorgante" "dos outorgantes" "das outorgantes"}}, praticando todos os actos de administração ordinária', exclusivo: true, tiposPermitidos: ['GERAL'] },
  { codigo: 'NOT-001', categoria: 'NOTARIADO', nome: 'Outorgar escrituras', descricao: 'Outorgar escrituras e documentos autenticados.', texto: 'outorgar escrituras públicas e documentos particulares autenticados relativos aos actos aqui previstos' },
  { codigo: 'OUT-001', categoria: 'OUTROS', nome: 'Poder de encerramento (actos necessários)', descricao: 'Fórmula instrumental de fecho.', texto: 'praticar todos os demais actos necessários, úteis e convenientes ao bom e cabal cumprimento do presente mandato' },
  // Cláusulas finais
  { codigo: 'CL-SUB', tipo: 'CLAUSULA', categoria: 'CLAUSULAS', nome: 'Substabelecimento', descricao: 'Permite substabelecer.', texto: 'Os poderes conferidos podem ser substabelecidos, no todo ou em parte, {{modo}}.', campos: [{ chave: 'modo', rotulo: 'Modo', tipo: 'RADIO', obrigatorio: true, opcoes: [{ valor: 'com', rotulo: 'com reserva' }, { valor: 'sem', rotulo: 'com ou sem reserva' }] }], regras: [INC('CL-NSUB')] },
  { codigo: 'CL-NSUB', tipo: 'CLAUSULA', categoria: 'CLAUSULAS', nome: 'Proibição de substabelecimento', descricao: 'Proíbe substabelecer.', texto: 'Os poderes conferidos não podem ser substabelecidos.' },
  { codigo: 'CL-VAL', tipo: 'CLAUSULA', categoria: 'CLAUSULAS', nome: 'Prazo de validade', descricao: 'Validade até data ou revogação.', texto: '{{#if data_fim}}A presente procuração é válida até {{data_fim}}.{{else}}A presente procuração produz efeitos a partir da data da sua assinatura e mantém-se em vigor até à sua revogação.{{/if}}', campos: [{ chave: 'data_fim', rotulo: 'Válida até (vazio = até revogação)', tipo: 'DATA', obrigatorio: false }] },
  { codigo: 'CL-IRR', tipo: 'CLAUSULA', categoria: 'CLAUSULAS', nome: 'Irrevogabilidade', descricao: 'Procuração conferida também no interesse do procurador (3% do corpus).', texto: 'A presente procuração é conferida também no interesse {{flex procuradores "do procurador" "da procuradora" "dos procuradores" "das procuradoras"}}, sendo irrevogável nos termos da lei.' },
  { codigo: 'CL-CONTAS', tipo: 'CLAUSULA', categoria: 'CLAUSULAS', nome: 'Prestação de contas', descricao: 'Dever de prestar contas.', texto: '{{flex procuradores "O procurador" "A procuradora" "Os procuradores" "As procuradoras"}} {{flex procuradores "deverá" "deverá" "deverão" "deverão"}} prestar contas dos actos praticados ao abrigo deste mandato.' },
];
